"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import settings
from setuptools import setup

APP_NAME = "Vocabulary_English"
APP = ['english_program.py']
DATA_FILES = [
    ( 'another_windows/setting', ['another_windows/setting/label_settings.xml']),
    ('database', ['database/'+'data_word.sqlite'],),
    ('languages', ['languages/'+'language_en.xml','languages/language_ru.xml','languages/language_ua.xml']),
    ('other', ['other/fonts/JetBrainsMono-Medium.ttf'])
]
OPTIONS = {
    'packages': [
'altgraph',
'asgiref',
'certifi',
'chardet',
'darkdetect',
'emoji',
'hpack',
'hstspreload',
'httpcore',
'httpx',
'hyperframe',
'idna',
'lxml',
'macholib',
'modulegraph',
'numpy',
'pandas',
'pynput',
'pytz',
'requests',
'six',
'sniffio',
'soupsieve',
'sqlparse',
'tabulate',
'urllib',
    ],
'iconfile':'test.png',
    'argv_emulation': True
}

setup(
    name = APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
